
export const ADD_HOSPITALS = "ADD_HOSPITALS";
export const HOSPITALS_LOADING = "HOSPITALS_LOADING";
export const HOSPITALS_FAILED = "HOSPITALS_FAILED";

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const ADD_PARTNERS = "ADD_PARTNERS";
export const PARTNERS_LOADING = "PARTNERS_LOADING";
export const PARTNERS_FAILED = "PARTNERS_FAILED";

export const ADD_COUNTRIES = 'ADD_COUNTRIES';
export const COUNTRIES_LOADING = 'COUNTRIES_LOADING';
export const COUNTRIES_FAILED = 'COUNTRIES_FAILED';