export const ADD_COMMENT = 'ADD_COMMENT';
export const HOSPITALS_LOADING = "HOSPITALS_LOADING";
export const HOSPITALS_FAILED = "HOSPITALS_FAILED";
export const ADD_HOSPITALS = "ADD_HOSPITALS";
export const ADD_COUNTRIES = 'ADD_COUNTRIES';